version: "3.7"

services:
  api:
    build:
      context: .
    ports:
      - 80:80
    environment:
      ESRGAN_MODEL_NAME: RealESRGAN_x4plus
      ESRGAN_TILE: 0
      ESRGAN_TILE_PAD: 10
      ESRGAN_PRE_PAD: 0
      ESRGAN_OUTPUT_SCALE: 2
      ESRGAN_FP32: "False"
      ESRGAN_FACE_ENCHANCE: "False"
      ESRGAN_ALPHA_UPSAMPLER: realesrgan
      ESRGAN_GPU_ID: 0

    volumes:
      - ./data:/api/data:rw

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia

